name: Deployment pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'

      - name: Check ESLint
        run: npm run lint

  format:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'
        
      - name: Check Prettier
        run: npm run format

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'

      - name: Run UI Tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'

      - name: Build Node Project
        run: npm run build 